url: https://imears.github.io
baseurl:

# Site settings
title: iMears
email: max@imears.com
description: "Hi, I'm Maxwell Mears! I'm a full-stack web developer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EB4E48
  secondary: ef6863
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Maxwell Mears
  pic: 1
  position: Full Stack Web Developer
  social:
    - title: twitter
      url: https://twitter.com/maxwell_mears
    - title: linkedin
      url: https://www.linkedin.com/in/maxwellmears
    - title: github
      url: http://github.com/imears

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/maxwell_mears
  - title: linkedin
    url: https://www.linkedin.com/in/maxwellmears
  - title: github
    url: http://github.com/imears

# Postal address (add as many lines as necessary)
address:
  - line: 4231 Manzanita Dr.
  - line: San Jose, CA 95129

# Build settings
markdown: kramdown
permalink: pretty